### ISSUE TITLE
Missing inventory Pz IV in !2PzD_DAK_PG_42_JAN composition

### ISSUE THREAD

**Issue by FakeMessiah27** [Drofseh/2PzD_Mission_Template#50]
**2.PzD Mission Template Version:** `2.7.0` (stable)

**Description:**
- Pz. IV spawns in without equipment in inventory for !2PzD_DAK_PG_42_JAN composition. 
"[this, "1942_G_Pzr"] call FNC_VehicleGearScript;" line appears to be missing in the init of the tank.

**Comment by Drofseh** [comment]
I think you mean DAK PG 43 Jan
Thanks, I'll fix it.
